A less stupid solution

diff --git a/iicmd b/iicmd
--- a/iicmd
+++ b/iicmd
@@ -47,16 +47,6 @@ qdb() {
     head -n1 $botdir/qdb/$date.qdb
 }
 
-qgrep() {
-    file="$(grep -rilh --include=[1-9]*.qdb $1 $botdir/qdb/)"
-    if [[ $? -eq 0 ]]
-    then
-        tail $file
-    else
-        echo "QDB entry not found"
-    fi
-}
-
 case "$cmd" in
     man)
         [[ -n "$nicks" ]] && printf -- "%s: %s\n" "$nicks" "${commands[*]}" || printf -- "%s: %s | " "$nick" "${commands[*]}"
@@ -75,7 +65,12 @@ case "$cmd" in
         qdb ${extra#/}
         ;;
     grep)
-        qgrep ${extra#/}
+        file="$(grep -rilh --include=[1-9]*.qdb "${extra#/}" $botdir/qdb/)"
+        if [[ $? -eq 0 ]]; then
+            tail "$file"
+        else
+            echo "QDB entry not found"
+        fi
         ;;
     fortune)
         printf -- "%s\n" "$(fortune -osea)"
